### PR TITLE
Add banks of Patna in the Data Table with Search Box

### PR DESCRIPTION
**Pull request by ank1traj**

### CODE REVIEW

**Review by pydevsg — CHANGES_REQUESTED** [review]
Great work @ank1traj , please share a screenshot of the above work after all these changes

**Review by pydevsg — APPROVED** [review]

**Comment by ank1traj** [comment]
@pydevsg I need to attach screenshot of changes in code or only front-end?

**Comment by ank1traj** [comment]
pr1
pr2

**Comment by pydevsg** [comment]
@ank1traj share the screenshot of your work in the frontend after doing **npm start**

**Comment by ank1traj** [comment]
pr

**Comment by pydevsg** [comment]
@ank1traj just the validation before merging your PR, please share the screen shot of bank table  Patna in the website.

**Comment by ank1traj** [comment]
gnome-shell-screenshot-36J8D0

Screenshot of bank table Patna in the website.

Issue number - 10

**Comment by pydevsg** [comment]
Great work @ank1traj :+1: , keep it up.
Please use local branch to commit files from next time onwards.

**Pull request merged**
